### ISSUE TITLE
用户名密码是什么啊

### ISSUE THREAD

**Issue by oceanchiu** [Imfondof/android_easyTableMore#1]

**Comment by imfondof** [comment]
https://github.com/imfondof/android_easyTableMore/blob/master/src/com/example/easytablemore/LoginActivity.java

账号必须九位数字，前两位为入学年，如15，代表的是2015年入学;之后三位为专业代码，如001;之后两位为班级代码，如01，最后两位为自己的序号，如01，加起来就是150010101
（密码和账号是一样的）
